name: 'Artifacts Cleanup'
on:
  schedule:
    - cron: '0 13 */7 * *'
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 0
