name: Go Build and Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: 'latest'
        # use ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build
        run: |
          # 下载依赖
          git clone https://github.com/gek64/displayController.git
          ln -s ${{ github.workspace }}/displayController ../displayController
          mkdir -p bin
          # 编译批量编译程序
          git clone https://github.com/gek64/gobuilder.git
          cd gobuilder
          go mod tidy
          go build -v -trimpath -ldflags "-s -w" -o "${{ github.workspace }}/gobuilder_runner"
          chmod +x "${{ github.workspace }}/gobuilder_runner"
          cd ${{ github.workspace }}
          # 编译所有支持的架构/系统对
          go mod tidy
          "${{ github.workspace }}/gobuilder_runner" -os windows -arch amd64 -d bin
          "${{ github.workspace }}/gobuilder_runner" -os windows -arch 386 -d bin
          # 显示文件路径(debug)
          # ls .. -R -las
          # 获取sha256 checksum
          sha256sum bin/* > bin/SHA256SUMS.txt
          # 获取版本信息
          echo "$(go run . -v)" > bin/version.txt
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_files
          path: bin/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_files
          path: bin

      - name: Read version
        run: |
          # 获取版本信息
          echo "VERSION=$(cat bin/version.txt)" >> $GITHUB_ENV
          rm -rf bin/version.txt
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
